---
# tasks file for git-repositories
- name: Make sure known_hosts is up to date
  lineinfile:
    path: ~/.ssh/known_hosts
    line: "{{ item }}"
    create: true
    mode: "0600"
  loop: "{{known_hosts}}"

- name: Remove 1Password ssh agent
  file:
    path: ~/.1password/agent.sock
    state: absent
  when: ansible_distribution == "MacOSX"

- name: Update Git Repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    bare: "{{ item.bare | default(omit) }}"
    update: true
  loop: "{{ git_repos }}"
  loop_control:
    label: "{{ item.dest }}"

- name: Check if 1Password ssh agent is active
  stat:
    path: ~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock
  register: one_password_agent

- name: Create ~/.1password/ if needed
  file:
    path: ~/.1password/
    state: directory
  when: one_password_agent.stat.exists

- name: Relink 1Password ssh agent
  file:
    path: ~/.1password/agent.sock
    src: ~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock
    state: link
  when: one_password_agent.stat.exists
