---
# tasks file for git-repositories
- name: Make sure known_hosts is up to date
  lineinfile:
    path: ~/.ssh/known_hosts
    line: "{{ item }}"
    create: true
    mode: "0600"
  loop: "{{known_hosts}}"

- name: Update Git Repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    bare: "{{ item.bare | default(omit) }}"
    key_file: "{{ item.key_file | default(omit) }}"
    update: true
  loop: "{{ git_repos }}"
  loop_control:
    label: "{{ item.dest }}"
