---
# tasks file for git-repositories
- name: Remove 1Password ssh agent
  file:
    path: ~/.1password/agent.sock
    state: absent
  when: ansible_distribution == "MacOSX"

- name: Update Git Repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    bare: "{{ item.bare | default(omit) }}"
    update: true
  loop: "{{ git_repos }}"
  loop_control:
    label: "{{ item.dest }}"

- name: Check if 1Password ssh agent is active
  stat:
    path: ~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock
  register: 1password_agent

- name: Relink 1Password ssh agent
  file:
    path: ~/.1password/agent.sock
    src: ~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock
    state: link
  when: 1password_agent.stat.exists
